image: silkeh/clang

stages:          # List of stages for jobs, and their order of execution
  - test

my-test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - make
    - ./ft_containers.ft

mli-test-vector:
  stage: test
  script:
    - cd testers/containers_test
    - echo; ! (./do.sh vector | grep "❌") 

mli-test-stack:
  stage: test
  script:
    - cd testers/containers_test
    - echo; ! (./do.sh stack | grep "❌") 

mazoise-test-vector:
  stage: test
  script:
    - apt update && apt install zsh valgrind -yqq
    - cd testers/42TESTERS-CONTAINERS
    - |
     echo; ! (./Run_tests.sh vector  | grep -Ev "mazoise test|reserve test" | grep "❌")        || (cd VECTOR
        for i in diff/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        for i in logs/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        for i in leak/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        exit 1)

mazoise-test-stack:
  stage: test
  script:
    - apt update && apt install zsh valgrind -yqq
    - cd testers/42TESTERS-CONTAINERS
    - |
     echo; ! (./Run_tests.sh stack  | grep "❌") || (cd STACK
        for i in diff/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        for i in logs/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        for i in leak/* ;do printf "%s\n-------------------\n" "$i"; cat "$i";done
        exit 1)

monkey-test-vector:
  stage: test
  script:
    - cd testers/ft_containers_monkey_tester 
    - printf "../../\ny\n\n" | ./setup.sh
    - echo; ! (./monkey.sh vector | grep differ)

monkey-test-stack:
  stage: test
  script:
    - cd testers/ft_containers_monkey_tester 
    - printf "../../\ny\n\n" | ./setup.sh
    - echo; ! (./monkey.sh stack | grep differ)
